app = "arctic-ice-weather"
primary_region = "dfw"

[build]

[env]
  PORT = "8001"

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/weather/forecast?lat=32.7767&lon=-96.7970"

[deploy]
  release_command = "echo 'Weather service deployment complete'"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
