app = "app-rawyclbe"
primary_region = "iad"

[build]
builder = "paketobuildpacks/builder:base"

[env]
PORT = "8000"
SECRET_KEY = "production-secret-key-change-me"
GOOGLE_SHEETS_SERVICE_ACCOUNT_JSON = ""

[[services]]
http_checks = []
internal_port = 8000
processes = ["app"]
protocol = "tcp"
script_checks = []

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[services.concurrency]
hard_limit = 100
soft_limit = 80
type = "connections"

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"
