# Global Fly.io configuration for Arctic Ice Solutions services

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8000"
  ENVIRONMENT = "production"
  API_BASE_URL = "https://api.yourchoiceice.com"
  CORS_ORIGINS = "https://yourchoiceice.com,https://api.yourchoiceice.com"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[deploy]
  release_command = "echo 'Arctic Ice Solutions service deployment complete'"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
