"""Add authentication tables - roles, user_roles, refresh_tokens, audit_logs

Revision ID: f67e6afb1a63
Revises: 144bf0b82782
Create Date: 2025-09-12 11:20:39.965447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f67e6afb1a63'
down_revision: Union[str, Sequence[str], None] = '144bf0b82782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
