app = "arctic-ice-monitoring"
primary_region = "dfw"

[build]

[env]
  PORT = "8002"
  MONITORING_EMAIL = "admin@yourchoiceice.com"

[http_service]
  internal_port = 8002
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "60s"
  method = "GET"
  timeout = "10s"
  path = "/monitoring/health"

[deploy]
  release_command = "echo 'Monitoring service deployment complete'"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
