app = "arctic-ai-imports"
primary_region = "dfw"

[build]

[env]
  PORT = "8003"

[http_service]
  internal_port = 8003
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[deploy]
  release_command = "echo 'AI Imports service deployment complete'"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
