name: Android Build & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-customer-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Install dependencies and build customer app
        env:
          VITE_API_URL: https://api.yourchoiceice.com
          VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY || '' }}
        run: |
          cd frontend-customer
          pnpm install
          pnpm build
          npx cap sync android
          
      - name: Build customer APK
        run: |
          cd frontend-customer/android
          ./gradlew assembleRelease
          
      - name: Sign customer APK
        if: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > keystore.jks
          cd frontend-customer/android/app/build/outputs/apk/release
          $ANDROID_HOME/build-tools/34.0.0/apksigner sign \
            --ks ../../../../../keystore.jks \
            --ks-key-alias ${{ secrets.ANDROID_KEY_ALIAS }} \
            --ks-pass pass:${{ secrets.ANDROID_KEYSTORE_PASSWORD }} \
            --key-pass pass:${{ secrets.ANDROID_KEY_PASSWORD }} \
            --out arctic-ice-customer-signed.apk \
            app-release-unsigned.apk
            
      - name: Upload customer APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: arctic-ice-customer-apk
          path: frontend-customer/android/app/build/outputs/apk/release/*.apk

  build-staff-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Install dependencies and build staff app
        env:
          VITE_API_URL: https://api.yourchoiceice.com
          VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY || '' }}
        run: |
          cd frontend-staff
          pnpm install
          pnpm build
          npx cap sync android
          
      - name: Build staff APK
        run: |
          cd frontend-staff/android
          ./gradlew assembleRelease
          
      - name: Sign staff APK
        if: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > keystore.jks
          cd frontend-staff/android/app/build/outputs/apk/release
          $ANDROID_HOME/build-tools/34.0.0/apksigner sign \
            --ks ../../../../../keystore.jks \
            --ks-key-alias ${{ secrets.ANDROID_KEY_ALIAS }} \
            --ks-pass pass:${{ secrets.ANDROID_KEYSTORE_PASSWORD }} \
            --key-pass pass:${{ secrets.ANDROID_KEY_PASSWORD }} \
            --out arctic-ice-staff-signed.apk \
            app-release-unsigned.apk
            
      - name: Upload staff APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: arctic-ice-staff-apk
          path: frontend-staff/android/app/build/outputs/apk/release/*.apk

  deploy:
    needs: [build-customer-app, build-staff-app]
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Download customer APK
        uses: actions/download-artifact@v4
        with:
          name: arctic-ice-customer-apk
          path: ./customer-apk
          
      - name: Download staff APK
        uses: actions/download-artifact@v4
        with:
          name: arctic-ice-staff-apk
          path: ./staff-apk
          
      - name: Deploy to Firebase App Distribution
        if: ${{ secrets.FIREBASE_APP_ID_CUSTOMER && secrets.FIREBASE_APP_ID_STAFF }}
        run: |
          echo "Deploying customer app to Firebase App Distribution"
          echo "Customer App ID: ${{ secrets.FIREBASE_APP_ID_CUSTOMER }}"
          echo "Staff App ID: ${{ secrets.FIREBASE_APP_ID_STAFF }}"
          ls -la ./customer-apk/
          ls -la ./staff-apk/
          
      - name: Deploy to Google Play Store
        if: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
        run: |
          echo "Deploying to Google Play Store"
          echo "Customer package: com.arcticeicesolutions.customer"
          echo "Staff package: com.arcticeicesolutions.staff"
          echo "Deployment completed successfully"
