name: Auto-merge PRs

on:
  pull_request:
    types: [opened, synchronize]
  check_suite:
    types: [completed]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.user.login == 'devin-ai-integration[bot]') ||
      (github.event_name == 'check_suite' && github.event.check_suite.pull_requests[0].user.login == 'devin-ai-integration[bot]')
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Auto-merge PR
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.event.check_suite.pull_requests[0].number }}
          method: squash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
