name: Deploy
on: 
  push:
    branches: [ main, devin/1752750425-arctic-ice-solutions-initial-commit ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Deployment handled by Devin Apps Platform"
